markdown: kramdown

lang:
  - en
  - es

baseurl: /

# URL of the Site
url: 'https://joseeelv.github.io/'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: CyberWiki
# Description of the Site
description: Bienvenido a mi web sobre hacking
# URL of Image of the Site
site-image: "/assets/images/favicon.png"
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: "/assets/images/favicon.png"

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "/assets/images/favicon.png"
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jose.venegasan@gmail.com
# twitter_username: thedevslot
# instagram_username: thedevslot
# linkedin_username: 
github_username: Joseeelv
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Jose Luis Venega
# URL for the Image of the Author
author-image: 
# 60 Words About the Author
author-about: Hola, soy Jose Luis Venega Sánchez, estudiante del grado de Ingeniería Informática en la Universidad de Cádiz y soy un apasionado del mundo de la Ciberseguridad.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Joseeelv

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

collections:
  projects:
    output: true

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
